### ISSUE TITLE
Sorcerian Ring not craftable anymore

### ISSUE THREAD

**Issue by McTrevor79** [Pocket-Plane-Group/Item_Upgrade#2]
BG2EE, latest 2.6 version
Item Upgrade version 45 
SCS version 34.3 
Tweaks Anthology version 9 
english install

I got the reaching ring from the harper questline, Lavoks ring of Acuity. Also got money and Rings of protection.

In the list of forgable items (Cromwell) there is no entry for the sorcerian ring. 

The ring of Preservation can be forged, so the Ring of Protection seems to get recognized. Please note I have the tweaks anthology component installed which allows one protection item to be combined with magical armor. I do not know, if this messes with the protection items.

I also used EE-Keeper to change the reaching ring into the  version created by the apprentices in the planar sphere. Same result.

**Comment by CamDawg** [comment]
Forging the Sorcerian Ring also requires the Amulet of Metaspell Influence.

**Comment by McTrevor79** [comment]
Yes, you are right. I forgot to mention this one. I have that too.

**Comment by CamDawg** [comment]
Is it a Ring of Protection +1, aka Ring of Princes, and not the +2 (Guard's Ring)?

And are you using the original or revised version, and are you trying to upgrade with Cromwell or Cespenar?

**Comment by McTrevor79** [comment]
I have both rings. Cromwell. Original, so a list of choices in one dialogue. Not clicking through all the things I don't want or have the materials for. 

Usually you need the base item for the option to appear even if you don't have all the ingredients. I don't remember which of the ingredients is the base item for the ring but I guess it is the culprit.

**Comment by CamDawg** [comment]
Aha, found it! It's an OR() trigger that is one item short--basically you'll only be able to advance if you have the Reaching Ring from the Harper HQ AND the Reaching Ring from the apprentices in the Planar Sphere. I'll check if Cespenar or the revised components have the bug as well, and then fix it for v47. 

Thanks for the help!

**Comment by McTrevor79** [comment]
Thanks for fixing it. So for now I could keeper in the other ring and would be able to forge the ring?

**Comment by CamDawg** [comment]
Yes. Right now the trigger is that you need to have the Reaching Ring from the Harper HQ (ohringwi) AND one of either ring08 (Reaching Ring from the apprentices) or ring08a (this is an old version of the Harper Reaching Ring from Fixpack; it now uses ohringwi). 

The bug is only affecting Cromwell in the original version.

**Comment by CamDawg** [comment]
Alright, closing the ticket as it's fixed in commit https://github.com/Pocket-Plane-Group/Item_Upgrade/commit/68841447aa0f747443393e844b716f4b63623ecd

And in the v47 release: https://github.com/Pocket-Plane-Group/Item_Upgrade/releases/tag/v47
